name: Android Release APK

on:
  workflow_dispatch: {}               # allow manual runs
  push:
    branches: [ main ]                # build on pushes to main
    tags: [ 'v*' ]                    # build + publish when you push a tag (e.g. v1.2.3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Java (Gradle uses JDK 17 with modern AGP)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3) (React Native) Install Node + deps so bundling works during assembleRelease
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      # 4) Restore keystore from secret
      - name: Restore release keystore
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/my-release-key.jks

      # 5) Inject signing values into Gradle
      - name: Configure Gradle signing
        run: |
          cat >> android/gradle.properties <<'EOF'
          MYAPP_UPLOAD_STORE_FILE=my-release-key.jks
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF


      # 6) Build signed release
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Assemble release
        working-directory: android
        run: ./gradlew clean assembleRelease

      # 7) Upload artifact (download from the workflow run)
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

  # OPTIONAL: when you push a tag like v1.2.3, attach the APK to a GitHub Release
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: dist

      - name: Create/Update GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: dist/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
